In [4]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('../Data/marketing_campaign.csv', sep=';')
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,...,5,0,0,0,0,0,0,3,11,0

In [13]:
duplicate_count = df.duplicated().sum()
print(f'Total Duplicate Rows Found: {duplicate_count}')
if duplicate_count > 0:
    df = df.drop_duplicates()
    print('Duplicate Rows Removed Successfully!')
else:
        print('No Duplicate Rows Found.')
print(f'Current Shape of Dataset: {df.shape}')

Total Duplicate Rows Found: 0
No Duplicate Rows Found.
Current Shape of Dataset: (2240, 29)

In [15]:
df.info()
df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'], format='%Y-%m-%d')
print("\n new data type of 'Dt_Customer':", df['Dt_Customer'].dtype)
df[['Dt_Customer']].head()

<class 'pandas.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   str
 3   Marital_Status       2240 non-null   str
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   str
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), str(3)
memory usage: 507.6 KB

 new data type of 'Dt_Customer': datetime64[us]

  Dt_Customer
0  2012-09-04
1  2014-03-08
2  2013-08-21
3  2014-02-10
4  2014-01-19

In [17]:
print("Missing values in Income before fix:", df['Income'].isnull().sum())
df['Income'] = df['Income'].fillna(df['Income'].median())
df = df[df['Year_Birth'] > 1900]
df = df[df['Income'] < 200000]
print("Missing values in Income after fix:", df['Income'].isnull().sum())
print(f"Data shape after removing anomalies: {df.shape}")

Missing values in Income before fix: 0
Missing values in Income after fix: 0
Data shape after removing anomalies: (2236, 29)

In [20]:
df['Marital_Status'] = df['Marital_Status'].replace({
'Alone': 'Single',
'Absurd': 'Single',
'YOLO': 'Single',
'Together': 'Married'
})
df['Education'] = df['Education'].str.strip()
df['Marital_Status'] = df['Marital_Status'].str.strip()
print("Cleaned Marital Status Categories:")
print(df['Marital_Status'].value_counts())

Cleaned Marital Status Categories:
Marital_Status
Married     1442
Single       486
Divorced     231
Widow         77
Name: count, dtype: int64

In [21]:
df.to_csv('../Data/cleaned_data.csv', index=False)
print('Cleaned data successfully saved to "../Data/cleaned_data.csv" !')

Cleaned data successfully saved to "../Data/cleaned_data.csv" !